=== api-evangelist/pokeapi/json-schema/pokeapi-location-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/pokeapi/refs/heads/main/json-schema/pokeapi-location-schema.json",
  "title": "Location",
  "description": "Pok\u00e9API Location schema.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "region": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "game_indices": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "areas": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Slug name of the referenced resource."
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "Canonical URL of the referenced resource."
          }
        }
      }
    }
  }
}

=== api-evangelist/pokeapi/examples/pokeapi-location-example.json
{
  "id": 1,
  "name": "example",
  "region": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "names": [
    {
      "name": "example"
    }
  ],
  "game_indices": [
    {}
  ],
  "areas": [
    {
      "name": "example",
      "url": "https://pokeapi.co/api/v2/example/1/"
    }
  ]
}
