=== api-evangelist/pokeapi/json-schema/pokeapi-move-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/pokeapi/refs/heads/main/json-schema/pokeapi-move-schema.json",
  "title": "Move",
  "description": "Pok\u00e9API Move schema.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "accuracy": {
      "type": "integer",
      "nullable": true
    },
    "effect_chance": {
      "type": "integer",
      "nullable": true
    },
    "pp": {
      "type": "integer"
    },
    "priority": {
      "type": "integer"
    },
    "power": {
      "type": "integer",
      "nullable": true
    },
    "contest_combos": {
      "type": "object",
      "nullable": true
    },
    "contest_type": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "contest_effect": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "damage_class": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "flavor_text": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          },
          "version": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "generation": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "meta": {
      "type": "object"
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "target": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "type": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    }
  }
}

=== api-evangelist/pokeapi/examples/pokeapi-move-example.json
{
  "id": 1,
  "name": "example",
  "accuracy": 1,
  "effect_chance": 1,
  "pp": 1,
  "priority": 1,
  "power": 1,
  "contest_combos": {},
  "contest_type": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "contest_effect": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "damage_class": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "effect_entries": [
    {}
  ],
  "flavor_text_entries": [
    {
      "flavor_text": "example"
    }
  ],
  "generation": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "meta": {},
  "names": [
    {
      "name": "example"
    }
  ],
  "target": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "type": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  }
}
