=== api-evangelist/pokeapi/json-schema/pokeapi-pokedex-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/pokeapi/refs/heads/main/json-schema/pokeapi-pokedex-schema.json",
  "title": "Pokedex",
  "description": "Pok\u00e9API Pokedex schema.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "is_main_series": {
      "type": "boolean"
    },
    "descriptions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "pokemon_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "entry_number": {
            "type": "integer"
          },
          "pokemon_species": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "region": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "version_groups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Slug name of the referenced resource."
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "Canonical URL of the referenced resource."
          }
        }
      }
    }
  }
}

=== api-evangelist/pokeapi/examples/pokeapi-pokedex-example.json
{
  "id": 1,
  "name": "example",
  "is_main_series": true,
  "descriptions": [
    {
      "description": "example"
    }
  ],
  "names": [
    {
      "name": "example"
    }
  ],
  "pokemon_entries": [
    {
      "entry_number": 1,
      "pokemon_species": {}
    }
  ],
  "region": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "version_groups": [
    {
      "name": "example",
      "url": "https://pokeapi.co/api/v2/example/1/"
    }
  ]
}
