=== api-evangelist/pokeapi/json-schema/pokeapi-item-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/pokeapi/refs/heads/main/json-schema/pokeapi-item-schema.json",
  "title": "Item",
  "description": "Pok\u00e9API Item schema.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "cost": {
      "type": "integer"
    },
    "fling_power": {
      "type": "integer",
      "nullable": true
    },
    "fling_effect": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "attributes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Slug name of the referenced resource."
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "Canonical URL of the referenced resource."
          }
        }
      }
    },
    "category": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "effect": {
            "type": "string"
          },
          "short_effect": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "version_group": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "game_indices": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "held_by_pokemon": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "sprites": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string",
          "nullable": true
        }
      }
    }
  }
}

=== api-evangelist/pokeapi/examples/pokeapi-item-example.json
{
  "id": 1,
  "name": "example",
  "cost": 1,
  "fling_power": 1,
  "fling_effect": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "attributes": [
    {
      "name": "example",
      "url": "https://pokeapi.co/api/v2/example/1/"
    }
  ],
  "category": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "effect_entries": [
    {
      "effect": "example",
      "short_effect": "example",
      "language": {}
    }
  ],
  "flavor_text_entries": [
    {
      "text": "example",
      "version_group": {},
      "language": {}
    }
  ],
  "game_indices": [
    {}
  ],
  "held_by_pokemon": [
    {}
  ],
  "names": [
    {
      "name": "example"
    }
  ],
  "sprites": {
    "default": "example"
  }
}
