=== api-evangelist/pokeapi/json-schema/pokeapi-ability-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/pokeapi/refs/heads/main/json-schema/pokeapi-ability-schema.json",
  "title": "Ability",
  "description": "Pok\u00e9API Ability schema.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "is_main_series": {
      "type": "boolean"
    },
    "generation": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "flavor_text": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          },
          "version": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    },
    "pokemon": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  }
}

=== api-evangelist/pokeapi/examples/pokeapi-ability-example.json
{
  "id": 1,
  "name": "example",
  "is_main_series": true,
  "generation": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "names": [
    {
      "name": "example"
    }
  ],
  "effect_entries": [
    {}
  ],
  "flavor_text_entries": [
    {
      "flavor_text": "example"
    }
  ],
  "pokemon": [
    {}
  ]
}
