=== api-evangelist/pokeapi/json-schema/pokeapi-stat-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/pokeapi/refs/heads/main/json-schema/pokeapi-stat-schema.json",
  "title": "Stat",
  "description": "Pok\u00e9API Stat schema.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "game_index": {
      "type": "integer"
    },
    "is_battle_only": {
      "type": "boolean"
    },
    "affecting_moves": {
      "type": "object"
    },
    "affecting_natures": {
      "type": "object"
    },
    "characteristics": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "format": "uri",
            "description": "Canonical URL of the referenced resource."
          }
        }
      }
    },
    "move_damage_class": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Slug name of the referenced resource."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "Canonical URL of the referenced resource."
        }
      }
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "Slug name of the referenced resource."
              },
              "url": {
                "type": "string",
                "format": "uri",
                "description": "Canonical URL of the referenced resource."
              }
            }
          }
        }
      }
    }
  }
}

=== api-evangelist/pokeapi/examples/pokeapi-stat-example.json
{
  "id": 1,
  "name": "example",
  "game_index": 1,
  "is_battle_only": true,
  "affecting_moves": {},
  "affecting_natures": {},
  "characteristics": [
    {
      "url": "https://pokeapi.co/api/v2/example/1/"
    }
  ],
  "move_damage_class": {
    "name": "example",
    "url": "https://pokeapi.co/api/v2/example/1/"
  },
  "names": [
    {
      "name": "example"
    }
  ]
}
